/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparer_2 (
    input [5:0] alufn,
    input z,
    input v,
    input n,
    output reg [7:0] ans
  );
  
  
  
  reg cmp;
  
  always @* begin
    
    case (alufn[0+2-:3])
      3'h3: begin
        cmp = z;
      end
      3'h5: begin
        cmp = n ^ v;
      end
      3'h7: begin
        cmp = z | n ^ v;
      end
      default: begin
        cmp = 1'h0;
      end
    endcase
    ans = 1'h0;
    ans[0+0-:1] = cmp;
  end
endmodule
